name 'setup-webserver'
maintainer 'Stew Snow'
maintainer_email 'stewart.snow@snowsd.com'
license 'all_rights'
description 'Installs/Configures setup-webserver'
long_description 'Installs/Configures setup-webserver'
version '0.1.10'

depends 'firewall', '~> 2.4.0'
depends 'httpd', '~> 0.3.5'
